### ISSUE TITLE
Unable to find apps to decrypt

### ISSUE THREAD

**Issue by illnino** [as0ler/r2clutch#1]
1. Install r2
2. `git clone git@github.com:as0ler/r2clutch.git`
3. `python r2Clutch.py`

It said

> No such file or directory: '/User/Containers/Bundle/Application'

May I know why the location isnt `/private/var/mobile/Containers/Data/Application`?

Btw, Clutch2 failed to decrypt Apps installed via TestFlight. Will r2Clutch work?
# 

Error Log:

``` bash
isrs-iPad:~/r2clutch root# python r2Clutch.py

  ***************************************************
  *      ____    ___ _       _       _              *
  *  _ _|___ \  / __\ |_   _| |_ ___| |__           *
  * | '__|__) |/ /  | | | | | __/ __| '_ \          *
  * | |  / __// /___| | |_| | || (__| | | |         *
  * |_| |_____\____/|_|\__,_|\__\___|_| |_|         *
  ***************************************************

Traceback (most recent call last):
  File "r2Clutch.py", line 210, in <module>
    listApps ()
  File "r2Clutch.py", line 35, in listApps
    containers = os.listdir( applicationPath )
OSError: [Errno 2] No such file or directory: '/User/Containers/Bundle/Application'
```

**Comment by illnino** [comment]
R2 Version: 

Version: radare2 0.10.6 12625

``` bash
isrs-iPad:~/r2clutch root# r2 -v
radare2 0.10.6 12625 @ darwin-arm-32 git.0.10.6-117-g503cb62
commit: 503cb6219d87dc667d1fb021496ad2d052b7f620 build: 2016-10-12
```

``` bash
➜  r2clutch git:(master) r2 -v
radare2 0.10.6 12625 @ darwin-x86-64 git.0.10.6-117-g503cb62
commit: 503cb6219d87dc667d1fb021496ad2d052b7f620 build: 2016-10-12
```

iOS: 9.3.3 (iPad mini 4)
OS: 10.11.6

**Comment by xiaoyue10131748** [comment]
Same problem
